all: cls_double cls_pointer_va va_1 va_pointer
	ssh iphone "cd /var/root && rm -f $^"
	scp $^ iphone:/var/root
	for test in $^; do \
		echo ""; \
		echo "*** $$test"; \
		ssh iphone "/var/root/$$test"; \
	done

libffi:
	make -C ../../

%: %.c libffi
	$$CC -Wall -pipe -Os $$CFLAGS -I../../aarch64-apple-darwin/include -I../../aarch64-apple-darwin $< -o $@.tmp ../../aarch64-apple-darwin/.libs/libffi.a $$LDFLAGS
	codesign -f -s "$$IOS_CERTID" $@.tmp
	mv $@.tmp $@

.PHONY: libffi
